// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1-emZ-9zn-6yBabcc5AcR9tt6IpEoKZs',
    appId: '1:873255446363:web:d11ccbb6949270b1b15c7e',
    messagingSenderId: '873255446363',
    projectId: 'halixm-minum',
    authDomain: 'halixm-minum.firebaseapp.com',
    storageBucket: 'halixm-minum.firebasestorage.app',
    measurementId: 'G-NPM9R2TFJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNXte7y77WMqfAu-eKYFEYNvMsiSBaH4',
    appId: '1:873255446363:android:31678280e192a9d6b15c7e',
    messagingSenderId: '873255446363',
    projectId: 'halixm-minum',
    storageBucket: 'halixm-minum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtdRg6JFssYntaJBwW3cHK2kRgqIJ46Q',
    appId: '1:873255446363:ios:d297d5f4068d5a16b15c7e',
    messagingSenderId: '873255446363',
    projectId: 'halixm-minum',
    storageBucket: 'halixm-minum.firebasestorage.app',
    iosClientId:
        '873255446363-9v372ib6baa046od59d2unm0uueet61t.apps.googleusercontent.com',
    iosBundleId: 'com.halixm.minum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJtdRg6JFssYntaJBwW3cHK2kRgqIJ46Q',
    appId: '1:873255446363:ios:d297d5f4068d5a16b15c7e',
    messagingSenderId: '873255446363',
    projectId: 'halixm-minum',
    storageBucket: 'halixm-minum.firebasestorage.app',
    iosClientId:
        '873255446363-9v372ib6baa046od59d2unm0uueet61t.apps.googleusercontent.com',
    iosBundleId: 'com.halixm.minum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1-emZ-9zn-6yBabcc5AcR9tt6IpEoKZs',
    appId: '1:873255446363:web:1d09767611793a97b15c7e',
    messagingSenderId: '873255446363',
    projectId: 'halixm-minum',
    authDomain: 'halixm-minum.firebaseapp.com',
    storageBucket: 'halixm-minum.firebasestorage.app',
    measurementId: 'G-TYPRMC0HW4',
  );
}
